# Generated by Django 3.0.5 on 2021-02-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210226_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=300, null=True, verbose_name='Жанр'),
        ),
    ]
