# Generated by Django 3.0.5 on 2021-02-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0002_auto_20210217_2259'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
