# Generated by Django 3.0.5 on 2021-02-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0003_auto_20210219_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
