# Generated by Django 3.0.5 on 2021-02-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0004_myuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
