# Generated by Django 3.0.5 on 2021-02-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0006_auto_20210220_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
