# Generated by Django 3.0.5 on 2021-02-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0006_remove_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
