# Generated by Django 3.0.5 on 2021-02-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0009_auto_20210222_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
