# Generated by Django 3.0.5 on 2021-02-22 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0017_auto_20210222_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api_v0.Title', verbose_name='Произведение'),
            preserve_default=False,
        ),
    ]
