# Generated by Django 3.0.5 on 2021-02-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0018_auto_20210222_1535'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review',
        ),
    ]
