# Generated by Django 3.0.5 on 2021-02-22 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0020_auto_20210222_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='review',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api_v0.Review', verbose_name='Комментарии'),
        ),
    ]
