# Generated by Django 3.0.5 on 2021-02-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0021_auto_20210223_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
