# Generated by Django 3.0.5 on 2021-02-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0022_auto_20210223_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
